apiVersion: v1
kind: ServiceAccount
metadata:
  name: datalake-ingestion
  namespace: datalake-ingestion
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datalake-ingestion
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: datalake-ingestion
    namespace: datalake-ingestion
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: datalake-ingestion
  namespace: datalake-ingestion
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "app"
      version: "v2"
      auth:
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "kubernetes"
          # A required field containing the Vault Role to assume.
          role: "datalake-ingestion"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: "datalake-ingestion"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datalake-ingestion
  namespace: datalake-ingestion
spec:
  refreshInterval: "15s" # time to sync from vault
  secretStoreRef:
    name: datalake-ingestion
    kind: SecretStore
  target:
    name: datalake-ingestion
    creationPolicy: Owner # create secret if not exists
  data:
    - secretKey: oidc-client-secret
      remoteRef:
        key: app/data/datalake-ingestion # path to secret in vault
        property: oidc-client-secret # key in the vault secret
    - secretKey: oidc-client-id
      remoteRef:
        key: app/data/datalake-ingestion # path to secret in vault
        property: oidc-client-id # key in the vault secret
