repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
        additional_dependencies: [tomli]
        exclude: "karabo/examples/.*.ipynb$"
    -   id: no-commit-to-branch
        args: [--branch, main]

# -   repo: https://github.com/pycqa/pydocstyle
#     rev: 6.3.0
#     hooks:
#     -   id: pydocstyle

-   repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
    -   id: black-jupyter

-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8

-   repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        name: isort (python)
