name: karabo_dev_env
channels:
  - i4ds
  - conda-forge
  - defaults
dependencies:
  - oskarpy=2.8.0
  - rascil=0.7.0
  - astropy
  - numpy>=1.21
  - dask
  - matplotlib
  - healpy
  - requests
  - astropy
#  - pinocchio # [linux]
  - katbeam
  - eidos
