name: karabo_env_test
channels:
  - i4ds
  - conda-forge
  - defaults
dependencies:
  - oskar=2.7.6
  - rascil=0.5.0
  - astropy
  - numpy>=1.21
  - dask
  - matplotlib
  - unittest-xml-reporting
  - healpy
