channels:
  - i4ds
  - i4ds/label/dev
  #- nvidia/label/cuda-11.7.0
  - nvidia/label/cuda-12.9.1
  - conda-forge
dependencies:
# Set dependencies and it's constraints in the package they belong. Otherwise you just cause chaos for future builds.
# Just Karabo's direct dependencies and Karabo constraints (from our code) should be handled here.
# Dependencies with unstable APIs (this usually includes Karabo-Feedstock) should be fixed.
# Don't fix anything regarding build-string (except mpi) here. There's a lot you could do wrong.
#
# IMPORTANT: If you add or remove dependencies, make sure to adjust conda/meta.yaml as well.
  - python                  >=3.11,<3.12
  - aratmospy               =1.0.dev0
  - astropy                 
  - bdsf                    =1.13.dev0.post2
  - bluebild                =0.1.dev0
  - casacore
  - cuda-cudart             >=12,<13 # =11.7
  - cuda-version            >=12,<13 # =11.7
  - dask                    >=2024.12, <2025.4 
  - dask-mpi                
  - distributed             
  - eidos                   =1.1.dev0
  - healpy
  - h5py                    =*=mpi_mpich*
  - ipython
  - katbeam                 =0.1.dev0
  - libcufft  
  - matplotlib
  - montagepy               =6.0.dev0
  - mpi4py
  - mpich
  - nbformat
  - nbconvert
  #- numpy                   >=1.21, !=1.24.0, <2.0  # upper-bounded because see issue #584 (here)
  - numpy                   >=2.1.3,<2.3
  - oskarpy                 =2.12.dev2
  - packaging
  - pandas
  - psutil
  - rascil                  =2.1.dev0
  - reproject               >=0.9,<=10.0
  - requests
  - rfc3986                 >=2.0.0
  # Dev RASCIL/SKA packages now require scipy >=1.15, so the old <1.15 pin is no longer compatible here.
  - scipy                   >=1.15
  - ska-gridder-nifty-cuda  =0.3.dev0
  - ska-sdp-datamodels      =1.0.dev0
  - ska-sdp-func-python     =1.0.dev0
  - tools21cm               =2.0.dev3
  - wsclean                 =3.6.dev0
  - xarray                  >=2024.9,<2024.11 # should not be pinned here =2022.11( upper bound is better )  # pinned because rascil=1.0.0 pulls ska-sdp-func-python=0.1.4, which hard-pins xarray=2023.2; https://gitlab.com/ska-telescope/sdp/ska-sdp-func-python/-/blob/main/pyproject.toml?ref_type=heads
  # transversal dependencies which we need to reference to get mpi-wheels
  # casacore hast just no-mpi & open-mpi, but no mpich-wheel
  - conda-forge::fftw       =*=mpi_mpich*  # oskarpy(oskar(casacore)), tools21cm, bluebild(finufft) -> from conda-forge to ignore channel-prio & not take our legacy fftw-wheel
  # exclude buggy versions of other tools
  - setuptools              !=71.0.0, !=71.0.1, !=71.0.2  # buggy with `importlib_metadata`
  # for MWA measurement set, uvfits, hdf5, mir support (choc-234)
  # this [casa] syntax won't work with mamba!
  #- pyuvdata[casa]          >=2.4,<3
  - pyuvdata                >=2.4,<3
  - python-casacore
