[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "mpi: mpi-tests (launch with: 'mpirun -n <n-processes> pytest .')",
]