FROM --platform=amd64 continuumio/miniconda3

RUN apt-get update && apt-get install -y curl && apt-get clean
RUN conda update conda
COPY ../environment-test.yaml environment-test.yaml
RUN conda env update --file environment-test.yaml --prune