# Create build container to not have copied filed in real container afterwards
FROM --platform=amd64 continuumio/miniconda3 as build
COPY ../environment.yaml environment.yaml
COPY ../requirements.txt requirements.txt

FROM --platform=amd64 continuumio/miniconda3
SHELL ["/bin/bash", "-c"]
# Adding libgl1-mesa-glx & xvfb because GitHub runners complain about pyvista import and test:
# ImportError: libGL.so.1: cannot open shared object file: No such file or directory
RUN apt-get update && apt-get install -y curl libgl1-mesa-glx xvfb && apt-get autoclean && rm -rf /var/lib/apt/lists/*
RUN conda update conda
# Add untitesting package needed for writing the nice github issue reporst into the env.yaml file.
COPY --from=build environment.yaml environment.yaml
COPY --from=build requirements.txt requirements.txt
RUN echo "\n  - unittest-xml-reporting" >> environment.yaml
RUN conda env update --file environment.yaml --prune
RUN pip install -r requirements.txt