FROM --platform=amd64 continuumio/miniconda3

RUN apt-get update &&  \
    apt-get install -y git gfortran build-essential curl && apt-get clean

RUN conda update conda && \
    conda install -c anaconda pip

RUN conda create -n karabo python=3.8
SHELL ["conda", "run", "-n", "karabo", "/bin/bash", "-c"]
RUN conda install -c i4ds -c conda-forge karabo-pipeline=0.2.0

RUN echo "conda activate karabo" >> ~/.bashrc
SHELL [ "/bin/bash" ]
