FROM --platform=amd64 jupyter/base-notebook

USER root

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    git \
    gfortran  \
    build-essential  \
    wget && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/* /var/log/dpkg.log

USER $NB_UID

RUN conda update conda && \
    conda install -c anaconda pip && \
    conda clean --all --yes
RUN pip install dask-labextension

RUN conda create -n karabo python=3.7
SHELL ["conda", "run", "-n", "karabo", "/bin/bash", "-c"]
RUN conda install -c i4ds -c conda-forge karabo-pipeline=0.2.0
RUN conda install -c conda-forge python-casacore=3.4.0

RUN pip install --index-url=https://artefact.skao.int/repository/pypi-all/simple rascil
RUN mkdir rascil_data && \
    cd rascil_data && \
    wget https://ska-telescope.gitlab.io/external/rascil/rascil_data.tgz -O rascil_data.tgz && \
    tar zxf rascil_data.tgz && \
    rm rascil_data.tgz && \
    cp -r ./data/ /opt/conda/envs/karabo/lib/python3.7/site-packages/rascil/data_models/../../data/

RUN conda install ipykernel
RUN ipython kernel install --user --name=karabo

USER root

RUN mkdir /home/jovyan/work/persistent/

RUN fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}" && \
    fix-permissions "${HOME}/work/persistent"

ENV JUPYTER_ENABLE_LAB=yes

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

USER $NB_UID
WORKDIR $HOME
