FROM --platform=amd64 jupyter/base-notebook

USER root

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    git \
    curl && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*

USER $NB_UID

RUN conda update conda && \
    conda install -c anaconda pip && \
    conda clean --all --yes
RUN pip install dask-labextension

# make env and kernel
RUN mamba create -n karabo
SHELL ["conda", "run", "-n", "karabo", "/bin/bash", "-c"]
RUN mamba install -c i4ds -c conda-forge karabo-pipeline ipykernel
RUN ipython kernel install --user --name=karabo

USER root

RUN mkdir /home/jovyan/work/persistent/

RUN fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}" && \
    fix-permissions "${HOME}/work/persistent"

ENV JUPYTER_ENABLE_LAB=yes

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

USER $NB_UID
WORKDIR $HOME
