FROM --platform=amd64 continuumio/miniconda3

RUN apt-get update &&  \
    apt-get install -y git gfortran build-essential curl && apt-get clean

RUN conda update conda

RUN conda create -n karabo
SHELL ["conda", "run", "-n", "karabo", "/bin/bash", "-c"]
RUN conda install -c i4ds -c conda-forge -c nvidia/label/cuda-11.7.0 karabo-pipeline

RUN echo "conda activate karabo" >> ~/.bashrc
SHELL [ "/bin/bash" ]
