{% set name = "Karabo-Pipeline" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  number: 0

requirements:
  build:
    - python
    - pip
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - matplotlib
    - oskarpy=2.8.0
    - rascil=0.5.0
    - requests
    - astropy
    - healpy
    - pinocchio # [linux]
    - katbeam
    - eidos

test:
  imports:
    - karabo

about:
  home: https://github.com/i4Ds/Karabo-Pipeline
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Astronomy data centric pipeline built for SKA (Square Kilometer Array) and beyond.'
  description: |
   Astronomy data centric pipeline built for SKA (Square Kilometer Array) and beyond.
  doc_url: https://github.com/i4Ds/Karabo-Pipeline/wiki
  dev_url: https://github.com/i4Ds/Karabo-Pipeline

extra:
  recipe-maintainers:
    - Christoph Vögele
