{% set name = "Karabo-Pipeline" %}

package:
  name: {{ name|lower }}
  version: {{ KARABO_VERSION }}

source:
  path: ../

build:
  number: {{ build }}
  string: py{{ py }}h{{ PKG_HASH }}_{{ build }}

# IMPORTANT: If you add or remove dependencies, make sure to adjust environment.yaml as well.
requirements:
  build:
    - python
    - numpy
  host:
    - python                  {{ python }}
    - pip
    - numpy
    - tomli
    - versioneer
  run:  # constrain-notes see `environment.yaml`
    - python                  {{ python }}
    - aratmospy               =1.0.0
    - astropy
    - bdsf                    =1.10.2
    - bluebild                =0.1.0
    - casacore
    - cuda-cudart
    - dask                    =2022.12.1
    - dask-mpi
    - distributed
    - eidos                   =1.1.0
    - healpy
    - h5py                    =*=mpi_mpich*
    - ipython
    - katbeam                 =0.1.0
    - libcufft
    - matplotlib
    - montagepy               =6.0.0
    - mpi4py
    - mpich
    - nbformat
    - nbconvert
    - numpy                   >=1.21, !=1.24.0, <2.0  # upper-bounded because see issue #584
    - oskarpy                 =2.8.3
    - packaging
    - pandas
    - psutil
    - rascil                  =1.0.0
    - reproject               >=0.9,<=10.0
    - requests
    - rfc3986                 >=2.0.0
    - scipy                   >=1.10.1
    - ska-gridder-nifty-cuda  =0.3.0
    - ska-sdp-datamodels      =0.1.3
    - ska-sdp-func-python     =0.1.4
    - tools21cm               =2.0.2
    - wsclean
    - xarray                  >=2022.11
    # transversal dependencies which we need to reference to get mpi-wheels
    - conda-forge::fftw       =*=mpi_mpich*
    # exclude buggy versions of other tools
    - setuptools              !=71.0.0, !=71.0.1, !=71.0.2  # buggy with `importlib_metadata`

test:
  imports:
    - karabo

about:
  home: https://github.com/i4Ds/Karabo-Pipeline
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Astronomy data centric pipeline built for SKA (Square Kilometer Array) and beyond.'
  description: |
   Astronomy data centric pipeline built for SKA (Square Kilometer Array) and beyond.
  doc_url: https://github.com/i4Ds/Karabo-Pipeline/wiki
  dev_url: https://github.com/i4Ds/Karabo-Pipeline

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
