{% set name = "Karabo-Pipeline" %}

package:
  name: {{ name|lower }}
  version: {{ KARABO_VERSION }}

source:
  path: ../

build:
  string: {{ KARABO_VERSION }}

requirements:
  build:
    - python=3.9
    - pip
  host:
    - python=3.9
    - pip
  run:
    - python=3.9
    - oskarpy=2.8.3
    - rascil=1.0.0
    - numpy=1.22
    - astropy
    - dask=2022.12.1
    - matplotlib
    - healpy
    - requests
    - pinocchio=5.0.0
    - katbeam=0.1.0
    - eidos=1.1.0
    - libcufft
    - cuda-cudart
    - ska-gridder-nifty-cuda=0.3.0
    - tools21cm=2.0.2
    - pytables=3.7.0


test:
  imports:
    - karabo

about:
  home: https://github.com/i4Ds/Karabo-Pipeline
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Astronomy data centric pipeline built for SKA (Square Kilometer Array) and beyond.'
  description: |
   Astronomy data centric pipeline built for SKA (Square Kilometer Array) and beyond.
  doc_url: https://github.com/i4Ds/Karabo-Pipeline/wiki
  dev_url: https://github.com/i4Ds/Karabo-Pipeline

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
