name: karabo_doc_env
channels:
  - i4ds
  - conda-forge
  - defaults
dependencies:
  - oskar=2.7.6
  - rascil=0.5.0
  - astropy
  - numpy>=1.21
  - dask
  - matplotlib
  - myst-parser
  - sphinx
  - sphinx_rtd_theme