# This is a template workflow that exists at the default branch for testing purpose at another branch.
# DO NOT CHANGE THIS WORKFLOW when you merge your branch to the default branch!

name: Dev Workflow

on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
