name: Test Karabo

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true

jobs:
  test-karabo:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge

      - name: Install Deps
        shell: bash -el {0}
        run: |
          PYTHON_VERSION=${{ inputs.python-version }}
          conda create -y -n test_karabo python=${{ inputs.python-version }}
          conda activate test_karabo
          mamba env update --file environment.yaml
          pip install -e ".[dev]"
          python -m ipykernel install --user --name python$PYTHON_VERSION

      - name: Test Dev-Tools
        shell: bash -l {0}
        run: |
          conda activate test_karabo
          flake8 .
          black --check .
          isort --check .
          mypy .

      - name: Test Code
        shell: bash -l {0}
        run: |
          conda activate test_karabo
          export IS_GITHUB_RUNNER=true RUN_GPU_TESTS=false RUN_NOTEBOOK_TESTS=true
          mpirun -n 2 pytest --only-mpi
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON
          fail_ci_if_error: false
          name: codecov-karabo
