name: Tests

on: [ push ]

jobs:
  Test_Karabo:
    runs-on: ubuntu-20.04
    container: ghcr.io/i4ds/karabo-pipeline:development
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test Code
        shell: bash -l {0}
        run: |
          conda activate karabo_dev_env
          python -m xmlrunner -o ./test-reports/junit
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Test-Results
          path: result
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-reports/**/*.xml
